apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: ghost
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 2368
