apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghost:4.41.3-alpine
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256M"
            cpu: "500m"
          requests:
            memory: "256M"
            cpu: "500m"
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://blog.acham.no
        volumeMounts:
                - mountPath: /var/lib/ghost/content
                  name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content