apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: ghost
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
